name: extended
channels:
  - conda-forge
  - bioconda
  - r
dependencies:
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - scikit-learn
  - scipy
  - statsmodels
  - biopython
  - pysam
  - pyvcf
  - bedtools
  - samtools
  - bcftools
  - blast
  - r-tidyverse
  - r-ggplot2
  - r-dplyr
  - r-readr
  - r-stringr
  - r-lubridate
  - r-data.table
  - r-plotly
  - r-dt
  - r-shiny
  - r-rmarkdown
  - r-knitr
  - r-devtools
  - r-roxygen2
  - r-testthat
  - r-lintr
  - bioconductor-biostrings
  - bioconductor-genomicranges
  - bioconductor-iranges
  - bioconductor-genomeinfodb
  - bioconductor-biomart
  - bioconductor-annotationdbi
  - bioconductor-deseq2
  - bioconductor-edger
  - bioconductor-limma
  - bioconductor-gostats
  - bioconductor-go.db
  - bioconductor-keggrest
  - bioconductor-reactome.db