version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.generated
      args:
        PROFILE: 
        ENABLE_BIOINFORMATICS: ${ENABLE_BIOINFORMATICS:-false}
    volumes:
      - ../..:/workspace:cached
      - ~/.ssh:/home/vscode/.ssh:ro
      - ~/.gitconfig:/home/vscode/.gitconfig:ro
    command: sleep infinity
    environment:
      - PROFILE=
      - ENABLE_JUPYTER=
      - ENABLE_RSTUDIO=
      - ENABLE_BIOINFORMATICS=${ENABLE_BIOINFORMATICS:-false}
    ports:
      - "8888:8888"  # Jupyter Lab
      - "8787:8787"  # RStudio Server
    networks:
      - devnet


  gatk-tools:
    image: broadinstitute/gatk:latest
    volumes:
      - ../..:/workspace:cached
      - ./data:/workspace/data
      - ./results:/workspace/results
    working_dir: /workspace
    profiles: ["bioinformatics", "gatk"]
    environment:
      - JAVA_OPTS=-Xmx8g
    networks:
      - devnet

  colabfold:
    image: colabfold/colabfold:latest
    volumes:
      - ../..:/workspace:cached
      - ./data:/workspace/data
      - ./models:/workspace/models
      - ./results:/workspace/results
    working_dir: /workspace
    profiles: ["structure", "colabfold"]
    environment:
      - CUDA_VISIBLE_DEVICES=0
    networks:
      - devnet

  autodock:
    image: ccsb/autodock-vina:latest
    volumes:
      - ../..:/workspace:cached
      - ./data:/workspace/data
      - ./results:/workspace/results
    working_dir: /workspace
    profiles: ["molecular", "autodock"]
    networks:
      - devnet

networks:
  devnet:
    driver: bridge

volumes:
  conda-cache:
  r-libs: